// GENERATED by sdk-gen (ymux 2.2.1) — DO NOT EDIT. Regenerate: npm run gen.
// WebSocket frame contract (PHASE-77-DESIGN §4.4). Discriminator: `type`.
package dev.ymux.sdk

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/** Shared Json with the frame discriminator + lenient unknown-key handling. */
object YmuxJson {
    val instance: Json = Json {
        classDiscriminator = "type"
        ignoreUnknownKeys = true
        encodeDefaults = false
    }
}

@Serializable
sealed interface YmuxFrame

@Serializable
@SerialName("hello")
data class HelloFrame(
    @SerialName("frame_version") val frameVersion: Long,
    @SerialName("session_id") val sessionId: String,
    @SerialName("client_id") val clientId: String
) : YmuxFrame

@Serializable
@SerialName("user_input")
data class UserInputFrame(
    val content: String,
    @SerialName("client_id") val clientId: String? = null,
    val seq: Long? = null,
    @SerialName("session_id") val sessionId: String? = null,
    val ts: Long? = null
) : YmuxFrame

@Serializable
@SerialName("hook_decision")
data class HookDecisionFrame(
    @SerialName("req_id") val reqId: String,
    val decision: String
) : YmuxFrame

@Serializable
@SerialName("interrupt")
data class InterruptFrame(
    @SerialName("client_id") val clientId: String? = null,
    val seq: Long? = null,
    @SerialName("session_id") val sessionId: String? = null,
    val ts: Long? = null
) : YmuxFrame

@Serializable
@SerialName("unsubscribe")
data object UnsubscribeFrame : YmuxFrame

@Serializable
@SerialName("hook_request")
data class HookRequestFrame(
    val seq: Long,
    @SerialName("session_id") val sessionId: String,
    val ts: Long,
    @SerialName("req_id") val reqId: String,
    @SerialName("tool_name") val toolName: String? = null,
    @SerialName("tool_input") val toolInput: JsonElement? = null,
    @SerialName("decision_required") val decisionRequired: Boolean? = null
) : YmuxFrame

@Serializable
@SerialName("hook_resolved")
data class HookResolvedFrame(
    val seq: Long,
    @SerialName("session_id") val sessionId: String,
    val ts: Long,
    @SerialName("req_id") val reqId: String,
    val decision: String,
    @SerialName("resolved_by") val resolvedBy: String
) : YmuxFrame

@Serializable
@SerialName("assistant_text")
data class AssistantTextFrame(
    val seq: Long,
    @SerialName("session_id") val sessionId: String,
    val ts: Long,
    val content: String
) : YmuxFrame

@Serializable
@SerialName("tool_use")
data class ToolUseFrame(
    val seq: Long,
    @SerialName("session_id") val sessionId: String,
    val ts: Long,
    @SerialName("tool_id") val toolId: String,
    @SerialName("tool_name") val toolName: String,
    @SerialName("tool_input") val toolInput: JsonElement? = null
) : YmuxFrame

@Serializable
@SerialName("tool_result")
data class ToolResultFrame(
    val seq: Long,
    @SerialName("session_id") val sessionId: String,
    val ts: Long,
    @SerialName("tool_id") val toolId: String,
    val content: String? = null,
    @SerialName("is_error") val isError: Boolean? = null
) : YmuxFrame

@Serializable
@SerialName("status")
data class StatusFrame(
    val seq: Long,
    @SerialName("session_id") val sessionId: String,
    val ts: Long,
    val status: String
) : YmuxFrame

@Serializable
@SerialName("error")
data class ErrorFrame(
    val seq: Long,
    @SerialName("session_id") val sessionId: String,
    val ts: Long,
    val message: String
) : YmuxFrame

@Serializable
@SerialName("notification")
data class NotificationFrame(
    val seq: Long,
    @SerialName("session_id") val sessionId: String,
    val ts: Long,
    val subkind: String? = null,
    val title: String? = null,
    val summary: String? = null
) : YmuxFrame

