// GENERATED by sdk-gen (ymux 2.2.1) — DO NOT EDIT. Regenerate: npm run gen.
// REST DTOs (generated from the server OpenAPI component schemas).
package dev.ymux.sdk

import kotlinx.serialization.*
import kotlinx.serialization.json.*

@Serializable
data class ClientInfo(
    @SerialName("client_id") val clientId: String,
    @SerialName("device_name") val deviceName: String,
    val files: List<String>,
    @SerialName("latest_entry") val latestEntry: Long,
    @SerialName("log_dir") val logDir: String
)

@Serializable
data class ClientsBody(
    val clients: List<ClientInfo>
)

@Serializable
data class CreateSessionRequest(
    val kind: String
)

@Serializable
data class ErrEvent(
    val error: String
)

@Serializable
data class ErrorDetail(
    val location: String? = null,
    val message: String? = null,
    val value: JsonElement? = null
)

@Serializable
data class ErrorModel(
    val detail: String? = null,
    val errors: List<ErrorDetail>? = null,
    val instance: String? = null,
    val status: Long? = null,
    val title: String? = null,
    val type: String? = null
)

@Serializable
data class FileEntry(
    val modified: Long,
    val name: String,
    val size: Long,
    val type: String
)

@Serializable
data class FileListBody(
    val cwd: String,
    val entries: List<FileEntry>
)

@Serializable
data class FormFile(
    val ContentType: String,
    val Filename: String,
    val IsSet: Boolean,
    val Size: Long
)

@Serializable
data class HealthBody(
    val ok: Boolean,
    @SerialName("uptime_seconds") val uptimeSeconds: Long,
    val version: String
)

@Serializable
data class HookDecisionRequest(
    val decision: String
)

@Serializable
data class HookForwardRequest(
    @SerialName("pane_id") val paneId: String,
    @SerialName("req_id") val reqId: String,
    @SerialName("timeout_at") val timeoutAt: Long,
    val title: String,
    @SerialName("tool_name") val toolName: String,
    @SerialName("workspace_id") val workspaceId: String
)

@Serializable
data class HookForwardResponse(
    val ok: Boolean,
    @SerialName("session_id") val sessionId: String
)

@Serializable
data class HookResolved(
    val decision: String,
    @SerialName("req_id") val reqId: String,
    val won: Boolean
)

@Serializable
data class HookStatus(
    val decision: String,
    val resolved: Boolean
)

@Serializable
data class LineEvent(
    val line: String
)

@Serializable
data class OkBody(
    val ok: Boolean
)

@Serializable
data class Pairing-redeemRequest(
    @SerialName("one_shot_token") val oneShotToken: String
)

@Serializable
data class PairingRedeemResponse(
    @SerialName("default_workspace_id") val defaultWorkspaceId: String,
    @SerialName("device_id") val deviceId: String,
    @SerialName("long_term_token") val longTermToken: String
)

@Serializable
data class PendingRequest(
    @SerialName("created_at") val createdAt: Long,
    @SerialName("req_id") val reqId: String,
    val resolution: String,
    @SerialName("resolved_by") val resolvedBy: String,
    @SerialName("session_id") val sessionId: String,
    @SerialName("timeout_at") val timeoutAt: Long,
    val type: String
)

@Serializable
data class ReadBody(
    val lines: List<String>,
    val truncated: Boolean
)

@Serializable
data class ScopesBody(
    val scopes: List<String>
)

@Serializable
data class Session(
    @SerialName("event_count") val eventCount: Long,
    val id: String,
    val kind: String,
    @SerialName("pending_requests") val pendingRequests: List<PendingRequest>,
    val subscribers: Long,
    @SerialName("workspace_id") val workspaceId: String
)

@Serializable
data class SessionCreated(
    val kind: String,
    @SerialName("session_id") val sessionId: String
)

@Serializable
data class UploadResultBody(
    val path: String,
    val sha256: String,
    val size: Long
)

@Serializable
data class VersionBody(
    @SerialName("api_versions") val apiVersions: List<Long>,
    @SerialName("frame_version") val frameVersion: Long,
    val name: String,
    val version: String
)

@Serializable
data class Workspace(
    @SerialName("active_session_count") val activeSessionCount: Long,
    @SerialName("created_at") val createdAt: Long,
    val id: String,
    val name: String
)

