// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * BRIEF: the Briefing-card options. Everything opt-in (defaults false) —
 * the card's automatic triggers must never surprise a user who didn't
 * ask for them; the manual shortcut works regardless of these.
 */
export type BriefOptions = {
/**
 * Show the card when switching into a workspace not visited for
 * `absence_minutes`.
 */
entry_card_on_return: boolean,
/**
 * Show the card on the first input after `idle_minutes` with no
 * keyboard/mouse activity in the app.
 */
entry_card_on_idle: boolean, absence_minutes: number, idle_minutes: number, };
