// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvVar = { key: string, value: string, /**
 * Secret rows keep their value out of workspaces.json and RPC output;
 * delivered only at spawn. Absent in legacy files → false.
 */
secret: boolean, };