// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 91: a multiplexer session a workspace has seen in sessions mode.
 *
 * Persisted so a session killed externally (reboot, `tmux kill-server`,
 * a kill from another client) stays in the strip greyed and can be
 * resumed: `claude --resume <claude_session_id>` in a fresh session of
 * the same name, started in `cwd`. Everything but `name` is optional and
 * elided, because a plain shell session has none of it.
 */
export type KnownSession = { name: string, 
/**
 * The display name the strip last showed (label / auto_name /
 * claude_title precedence, resolved by the frontend). `None` when it
 * was just the raw name.
 */
display: string | null, 
/**
 * The Claude session UUID that was running inside it — the `--resume`
 * target. Kept across refreshes that report `None`, so a session whose
 * hooks went quiet does not lose its resume handle.
 */
claude_session_id: string | null, 
/**
 * `cwd ?? owner_cwd` of the live row — where a resume should land.
 * `claude --resume` from `$HOME` on a root workspace with no `cwd`
 * would not find the project's transcript.
 */
cwd: string | null, 
/**
 * Unix seconds of the last refresh that listed it live.
 */
last_seen: bigint, };
