// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalSetupInput = { 
/**
 * LocalStepKind names, in execution order (the wizard sends only
 * the needed ones; unknown names fail their step, not the run).
 */
steps: Array<string>, distro: string | null, workspace_name: string | null, create_workspace: boolean, workspace_cwd: string | null, };