// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalSetupResult = { run_id: string, workspace_id: string | null, workspace_name: string | null, 
/**
 * Steps that errored, in run order. The done screen must not claim
 * success while this is non-empty — a failed WSL chain silently
 * skips workspace creation, which used to render as a clean finish.
 */
failed_steps: Array<string>, 
/**
 * Chain steps abandoned because an earlier chain step failed.
 */
skipped_steps: Array<string>, 
/**
 * True when the WSL chain ran and came out clean. When false with a
 * non-empty `failed_steps`, no WSL workspace exists.
 * macOS: same flag, but the "chain" is the tmux persistence chain
 * (`InstallTmuxLocal` → `DeployTmuxConfLocal`) — true means it ran
 * clean; a Local workspace is still created when no chain step was
 * requested at all.
 */
persistence_chain_ok: boolean, };