// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneBrief } from "./PaneBrief";

export type PaneBriefEntry = { brief: PaneBrief | null, last_prompt: string | null, prompt_ms: number | null, session_ended: boolean, seq: number, };
