// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefStatus } from "./BriefStatus";

export type PaneBrief = { task: string | null, status: BriefStatus, ask: string | null, rec: string | null, next: string | null, delta: string | null, degraded: boolean, updated_ms: number, };
