// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefOptions } from "./BriefOptions";
import type { ClaudeOptions } from "./ClaudeOptions";
import type { ClaudeUsageSettings } from "./ClaudeUsageSettings";
import type { FloatingWindows } from "./FloatingWindows";
import type { Font } from "./Font";
import type { HookSettings } from "./HookSettings";
import type { Hooks } from "./Hooks";
import type { HooksUpdates } from "./HooksUpdates";
import type { I18n } from "./I18n";
import type { LogsSettings } from "./LogsSettings";
import type { MigrationFlags } from "./MigrationFlags";
import type { Notifications } from "./Notifications";
import type { Shortcuts } from "./Shortcuts";
import type { SttSettings } from "./SttSettings";
import type { TerminalSettings } from "./TerminalSettings";
import type { Theme } from "./Theme";
import type { Updates } from "./Updates";

export type Settings = { version: number, theme: Theme, font: Font, terminal: TerminalSettings, hooks: Hooks, notifications: Notifications, updates: Updates, i18n: I18n, 
/**
 * Phase 16. `#[serde(default)]` so pre-16 settings.json files
 * load with the built-in defaults.
 */
shortcuts: Shortcuts, 
/**
 * Phase 17. Claude session summary options.
 */
claude: ClaudeOptions, 
/**
 * Phase 78. Claude subscription-usage indicator display + auto-refresh.
 */
claude_usage: ClaudeUsageSettings,
/**
 * BRIEF. Briefing-card triggers (all opt-in).
 */
brief: BriefOptions,
/**
 * Phase 18. Hooks-outdated banner show/skip state.
 */
hooks_updates: HooksUpdates, 
/**
 * Phase 32.B. When true, suppress the "set up SSH key
 * authentication?" offer after a password-auth connect. Persisted
 * when the user ticks "Don't show again" in the offer modal.
 * `#[serde(default)]` so older settings.json loads cleanly.
 */
ssh_key_offer_disabled: boolean, 
/**
 * Phase 41. When true (default), activating an SSH workspace
 * establishes a background SSH session so the tmux session picker and
 * the remote file manager populate without the user opening a
 * terminal pane first. Disable to defer the connection until a pane
 * connects. `default = "default_true"` keeps pre-41 settings.json
 * backwards-compatible (missing field → true).
 */
auto_connect_on_workspace_select: boolean, 
/**
 * Phase 80. When true, app start re-attaches the active workspace's SSH
 * panes to the tmux sessions they were on when it closed. OFF by default
 * and deliberately opt-in: it makes startup do network work — one SSH
 * handshake per restored pane, each re-running the workspace's
 * `setup_command` — which a rate-limited or fail2ban-fronted host will
 * notice. `#[serde(default)]` → missing field is false, so an existing
 * settings.json keeps the old startup behavior until the user asks.
 */
restore_sessions_on_start: boolean, 
/**
 * Phase 80.1. When true, the file manager reopens at the last directory
 * each column was showing (per workspace) instead of `$HOME`. OFF by
 * default so the pre-80.1 behavior is what an untouched install gets.
 */
file_manager_remember_path: boolean, 
/**
 * Phase 49-C: optional auto-delete of empty + stale workspaces at
 * startup. `None` (default) = disabled. Range 1-90 days enforced
 * by the UI; the backend sweep treats any non-zero positive value
 * as a valid TTL. A workspace is "empty" for sweep purposes when
 * it has no live SSH sessions and its `last_active_at` is older
 * than the TTL.
 */
auto_destroy_empty_workspaces_days: number | null, 
/**
 * Phase 39.B. One-time data migrations that have already run.
 */
migrations: MigrationFlags, 
/**
 * Phase 58. Voice input (speech-to-text). Default backend is the
 * browser-native Web Speech API; users with privacy / offline
 * needs can point at a local Whisper-compatible endpoint.
 * `#[serde(default)]` so older settings.json files load with
 * `enabled = false` + the default backend.
 */
stt: SttSettings, 
/**
 * Phase 62.B (item I): sidebar display mode — "full" | "icons" |
 * "hidden". A String (not an enum) to match the rtl_mode /
 * matcher_mode pattern and keep the TS binding a plain union.
 * Persisted here (atomic settings write, Rule #7) so the choice
 * survives restarts. `default = "full"` keeps older settings.json
 * loading unchanged. Phase 65.P: only "full" / "icons" are written
 * now; a legacy "hidden" value is migrated to "icons" on the
 * frontend at read time (App.tsx sidebarMode()).
 */
sidebar_mode: string, 
/**
 * Phase 63: per-kind (browser / filemanager) floating-window state —
 * which of the 3 modes each is in, plus the remembered geometry for
 * Float / Pop-out / Pane. `#[serde(default)]` so older settings.json
 * loads with both kinds defaulting to Float (current behavior).
 */
floating_windows: FloatingWindows, 
/**
 * Phase 75: debug-log hygiene (retention). `#[serde(default)]` so older
 * settings.json files load with the built-in defaults.
 */
logs: LogsSettings, 
/**
 * Unshipped-fivefer (#3): keep workspace-browser cookies/logins across
 * restarts. Backed by a single app-wide WebView2 profile folder (NOT a
 * per-workspace `--user-data-dir` — that reintroduces the 0x8007139F
 * crash). When false, the profile folder is wiped on the next launch.
 * `default = true`.
 */
persist_browser_sessions: boolean, 
/**
 * beta.3: which hook types the backend processes, and which of those
 * play a sound on the toast. Kept in its own struct so the settings.rs
 * `Hooks` block (policy engine / matcher_mode / auto_install) stays
 * scoped to CLI-side hook installation, while this new struct is
 * purely about desktop-side event routing + sound feedback.
 *
 * **Naming note:** the task brief called this field `hooks`, but that
 * name is taken by the existing policy-engine struct. Named
 * `hook_notifications` here to preserve backwards-compat without
 * migrating the old field. `#[serde(default)]` fills defaults when a
 * pre-beta.3 settings.json loads.
 */
hook_notifications: HookSettings, 
/**
 * Design Pass 01 (#2): dark/light appearance axis — "dark" | "light" |
 * "system". Independent of the colour preset: dark reuses the preset
 * engine as-is, "light" applies ymux's daylight chrome palette,
 * "system" follows the OS (`prefers-color-scheme`). A String (not an
 * enum) to match the sidebar_mode / rtl_mode pattern and keep the TS
 * binding a plain union. `default = "system"` keeps older settings.json
 * loading unchanged.
 */
theme_mode: string, 
/**
 * Phase 81: tmux session picker scope — "shared" (default) shows every
 * session on the server (multi-machine: home sees office sessions and
 * vice versa); "local" hides sessions whose recorded origin is another
 * machine (origin-less legacy sessions stay visible — fail-open). A
 * String (not an enum) per the sidebar_mode / theme_mode pattern.
 */
session_visibility: string, };