// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RtlProfiles } from "./RtlProfiles";

export type TerminalSettings = { 
/**
 * Phase 15.A: how to handle Hebrew / Arabic in the terminal.
 * One of "auto_per_line" (default, Termius-style — DOM renderer
 * + dir="auto" on every row), "force_rtl" (DOM renderer, every row
 * forced RTL), "bidi_reorder" (legacy v1, WebGL + bidi-js
 * logical→visual reorder), or "off" (WebGL, no reorder).
 * New panes pick up the renderer immediately; live mode swaps
 * affect the reorder pipeline on currently-open panes.
 */
rtl_mode: string, 
/**
 * Phase tmux-conf: when true (default), tmux is launched with
 * `-f ~/.ymux/tmux.conf` (and re-sources it on every attach) so the
 * bundled config applies: mouse OFF so clicks and drag-select stay
 * native, no status bar, the prefix table reduced to `[` / `d` /
 * `C-b`, PageUp as keyboard scrollback, 50k-line buffer, sane
 * truecolour (Phase 91.B). Set false to fall back to the user's own
 * `~/.tmux.conf`. The conf file is uploaded by the bootstrap
 * regardless, so the toggle takes effect on the NEXT pane connect.
 * `alias`: settings.json files written before the winmux → ymux
 * rename carry the old key. Without it a user who had explicitly
 * turned this OFF would silently get it back on after upgrading,
 * because the unknown key falls through to `default_true`.
 */
use_ymux_tmux_config: boolean, 
/**
 * Phase HH: mirror the physical Left/Right arrow keys when the
 * terminal line under the cursor is right-to-left (Hebrew/Arabic).
 * In an RTL line the visual "right" is logical "left", so without
 * this the arrows feel inverted. Only takes effect on RTL lines —
 * LTR lines are unaffected — so it's safe to leave on (default true).
 */
mirror_arrows_rtl: boolean, 
/**
 * v0.4.4 (RTL Approach C): auto-flip each terminal line's paragraph
 * direction from its text — a line with any Hebrew/Arabic char renders
 * RTL (mixed or pure), a pure-Latin line renders LTR. Only affects the
 * `auto_per_line` rtl_mode. Default true; set false for classic
 * LTR-only terminal behaviour.
 */
auto_direction: boolean, 
/**
 * 2026-08-18: force every row LTR while a self-bidi TUI (Claude Code)
 * holds the pane. Written in 2026-07 because Claude 2.1.74–2.1.210
 * emitted Hebrew ALREADY in visual order, so the per-line RTL pass
 * bidi'd it a second time and scrambled it.
 *
 * DEFAULT FALSE, and that is the whole point: current Claude
 * (verified live against claude-fable-5) emits Hebrew in LOGICAL
 * order like any other program, so forcing LTR is now what breaks
 * it. Measured on a live local pane — Hebrew scrambled with this on,
 * correct with it off, while SSH panes were never affected because
 * tmux swallows the OSC title the detector depends on.
 *
 * Kept rather than deleted because the visual-order behaviour was
 * real one month ago and may still be, on an older Claude or another
 * self-bidi TUI. Detection and its `tui-owns-bidi` log line run
 * regardless of this flag; only the LTR forcing is gated.
 */
tui_owns_bidi: boolean, 
/**
 * v0.4.4-beta.2: on connect/attach, clear stale mouse-tracking modes an
 * unclean app exit (vim/fzf/less/htop killed) can leave on — which makes
 * the bare shell print `\e[<..M` mouse escapes as text. Default true; a
 * manual "Reset terminal" (Ctrl+Alt+R) is always available regardless.
 */
auto_reset_on_connect: boolean, 
/**
 * 2026-08-19: the RTL knobs above, split per pane class. See
 * `RtlProfiles` for the measurement that forced the split.
 *
 * The four flat fields (`rtl_mode`, `auto_direction`,
 * `mirror_arrows_rtl`, `tui_owns_bidi`) are DEPRECATED and kept only so
 * an existing settings.json still loads and can be migrated from. On
 * load, when `rtl` is absent, `migrate_rtl_profiles` seeds the profiles:
 * each takes its own measured `rtl_mode` (a single pre-split value was
 * necessarily wrong for one of the two classes), while the other three
 * knobs carry over from the flat fields. Delete the flat fields a
 * release later, not here.
 *
 * `Option` on purpose: **absent is the migration signal.** A fresh
 * install gets `Some(RtlProfiles::default())` — the measured per-class
 * defaults — while an existing settings.json has no `rtl` key at all,
 * deserialises to `None`, and goes through the migration instead. The
 * two cases want different answers and a plain `#[serde(default)]`
 * could not tell them apart.
 */
rtl: RtlProfiles | null, };